// Generated by CoffeeScript 1.8.0
(function() {
  var Mixin;

  Mixin = function(model_name, event_name, cb_name) {
    var eventCbName, mixin;
    if (event_name == null) {
      event_name = "all";
    }
    eventCbName = "_eventCbs_" + model_name + "_" + event_name + "_" + (cb_name || '');
    mixin = {
      componentDidMount: function() {
        return this.props[model_name].on(event_name, this[eventCbName], this);
      },
      componentWillUnmount: function() {
        return this.props[model_name].off(event_name, this[eventCbName], this);
      }
    };
    mixin[eventCbName] = function() {
      if ((cb_name != null) && (this[cb_name] != null)) {
        return this[cb_name]();
      } else {
        return this.forceUpdate();
      }
    };
    return mixin;
  };

  module.exports = {
    Mixin: Mixin,
    ModelMixin: Mixin,
    CollectionMixin: Mixin
  };

}).call(this);
